import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const open=async(page:import('@playwright/test').Page,path='/review-packs?preview=1')=>{await page.goto(path);await expect(page.getByRole('heading',{name:'Better context. Better reviews.'})).toBeVisible();await expect(page.getByRole('button',{name:'Download Markdown',exact:true})).toBeEnabled();};
test('requirement action opens an exact, single-requirement review pack',async({page})=>{await page.goto('/requirements/FN-BKG-01?preview=1');await page.getByRole('link',{name:'Review with AI',exact:true}).click();await expect(page.getByLabel('Review scope')).toHaveValue('requirement:FN-BKG-01');const preview=page.getByRole('textbox',{name:'Exact context preview',exact:true});await expect(preview).toContainText('Review targets: FN-BKG-01.');await expect(preview).toContainText('FN-BKG-01-q01');await expect(preview).toContainText('END OF WERIDE REVIEW PACK');await expect(page.getByRole('button',{name:'Create share link',exact:true})).toHaveCount(0);await page.screenshot({path:'test-results/ai-review-requirement.png',fullPage:true});});
test('matrix pack downloads all 30 requirements, defaults to English and excludes estimates',async({page})=>{await open(page);await expect(page.getByLabel('Review scope')).toHaveValue('all');await expect(page.getByLabel('Agent response language')).toHaveValue('en');await expect(page.getByLabel('Recorded hours and costs',{exact:true})).not.toBeChecked();const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Download Markdown',exact:true}).click();const download=await wait;expect(download.suggestedFilename()).toMatch(/^weride-matrix-.*\.md$/);const body=await readFile((await download.path())!,'utf8');expect(body).toContain('Directory: 30 requirements');expect(body).toContain('Included collaboration items: 150');expect(body).toContain('printed pp.3–4');expect(body).not.toContain('createdByName');});
test('module scope and item type selection update coverage without silent truncation',async({page})=>{await open(page);await page.getByLabel('Review scope').selectOption('module:C');const preview=page.getByRole('textbox',{name:'Exact context preview',exact:true});await expect(preview).toContainText('Included collaboration items: 30');await page.getByLabel('Q&A',{exact:true}).uncheck();await expect(preview).toContainText('Included collaboration items: 24');await expect(preview).toContainText('Omitted within selected scope: 6');await expect(preview).toContainText('EXP-DRV-01');});
test('translations, creator notes, redaction and mobile layout work',async({page})=>{await open(page,'/review-packs?requirement=FN-BKG-01&preview=1');await page.getByLabel('Agent response language').selectOption('sv');await page.getByLabel('Review focus (optional)').fill('Check edge cases. Contact reviewer@madison.dev.');const preview=page.getByRole('textbox',{name:'Exact context preview',exact:true});await expect(preview).toContainText('Answer in Swedish');await expect(preview).toContainText('[email redacted]');expect(await preview.inputValue()).not.toContain('reviewer@madison.dev');await page.getByLabel('Display language',{exact:true}).selectOption('vi');await expect(page.getByRole('button',{name:'Sao chép prompt + context',exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/ai-review-mobile-vi.png',fullPage:true});});
test('copy context succeeds without contacting a model or sharing service',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await open(page,'/review-packs?requirement=FN-BKG-01&preview=1');await page.getByRole('button',{name:'Copy prompt + context',exact:true}).click();const copied=await page.evaluate(()=>navigator.clipboard.readText());expect(copied).toContain('FN-BKG-01');expect(copied).toContain('END OF WERIDE REVIEW PACK');await expect(page.locator('.toast')).toContainText('Copied.');});
test('related context retains separate target and supporting scope',async({page})=>{await open(page,'/review-packs?requirement=FN-BKG-01&preview=1');await page.locator('summary').filter({hasText:'Related context'}).click();await page.getByRole('checkbox',{name:/FN-DIS-01/}).check();await expect(page.getByRole('textbox',{name:'Exact context preview',exact:true})).toContainText('Additional context selected by the creator: FN-DIS-01.');await expect(page.getByRole('textbox',{name:'Exact context preview',exact:true})).toContainText('Role: selected-related-context');});
