import {before,after,beforeEach,test} from 'node:test';
import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,updateDoc,deleteDoc,serverTimestamp,writeBatch} from 'firebase/firestore';
let env;const base='workspaces/weride',loc=(en='')=>({en,vi:'',sv:''});
const context=(uid='alice',extra={})=>env.authenticatedContext(uid,{email:`${uid}@madison.dev`,email_verified:false,auth_time:Math.floor(Date.now()/1000),firebase:{sign_in_provider:'microsoft.com'},...extra}).firestore();
const ref=(db,type,id)=>doc(db,base,type,id);
const q=(id='question',extra={})=>({id,requirementId:'FN-BKG-01',kind:'qa',parentId:'',title:loc('Original question'),body:loc(),answer:loc(),acceptance:loc(),status:'open',priority:'high',owner:'',estimateHours:null,version:1,origin:'team',createdBy:'alice',createdByName:'Alice',updatedBy:'alice',updatedByName:'Alice',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),...extra});
const reply=(id='reply',extra={})=>({id,questionId:'question',body:{en:'',vi:'Trả lời bằng tiếng Việt',sv:''},originalLocale:'vi',version:1,createdBy:'bob',createdByName:'Bob',updatedBy:'bob',updatedByName:'Bob',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),...extra});
const resolution=(extra={})=>({id:'question',replyId:'reply',replyVersion:1,version:1,updatedBy:'alice',updatedByName:'Alice',updatedAt:serverTimestamp(),...extra});
const decision=(extra={})=>({id:'decision',title:loc('Proposed delivery decision'),body:loc('Evidence-backed proposal'),originalLocale:'en',state:'proposed',source:'',ownerUid:'',requirementIds:['FN-BKG-01'],version:1,createdBy:'alice',createdByName:'Alice',updatedBy:'alice',updatedByName:'Alice',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),confirmedBy:'',confirmedAt:null,...extra});
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-weride',firestore:{host:'127.0.0.1',port:8089,rules:readFileSync('firestore.rules','utf8')}});});
after(async()=>env?.cleanup());
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,base),{name:'WeRide'});await setDoc(ref(db,'requirements','FN-BKG-01'),{id:'FN-BKG-01'});await setDoc(ref(db,'entries','question'),q());});});
for(const language of ['en','vi','sv'])test(`native ${language} question needs no fabricated English`,async()=>{const title={en:'',vi:'',sv:'',[language]:'Native question'};await assertSucceeds(setDoc(ref(context(),'entries','native'),q('native',{originalLocale:language,title})));});
test('native language and bounds are validated server-side',async()=>{for(const extra of [{originalLocale:'xx'},{originalLocale:'vi',title:loc('Wrong language')},{originalLocale:'sv',title:{...loc(),sv:'x'.repeat(2001)}}])await assertFails(setDoc(ref(context(),'entries','bad'),q('bad',extra)));});
test('member can answer another asker in a separate reply without modifying the question',async()=>{await assertSucceeds(setDoc(ref(context('bob'),'replies','reply'),reply()));await assertSucceeds(getDoc(ref(context(),'replies','reply')));await assertFails(updateDoc(ref(context('bob'),'entries','question'),{title:loc('Hijack'),version:2,updatedBy:'bob',updatedAt:serverTimestamp()}));});
test('reply body cannot spoof authors or reference absent questions',async()=>{for(const extra of [{createdBy:'alice'},{questionId:'absent'},{body:loc()},{originalLocale:'xx'}])await assertFails(setDoc(ref(context('bob'),'replies','reply'),reply('reply',extra)));});
test('reply author can edit and delete an unaccepted reply; other members cannot',async()=>{await setDoc(ref(context('bob'),'replies','reply'),reply());await assertFails(updateDoc(ref(context(),'replies','reply'),{body:loc('Not mine'),originalLocale:'en',version:2,updatedBy:'alice',updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(ref(context('bob'),'replies','reply'),{body:loc('My revision'),originalLocale:'en',version:2,updatedAt:serverTimestamp()}));await assertSucceeds(deleteDoc(ref(context('bob'),'replies','reply')));});
test('only asker accepts a real reply at its current version',async()=>{await setDoc(ref(context('bob'),'replies','reply'),reply());await assertFails(setDoc(ref(context('bob'),'resolutions','question'),resolution({updatedBy:'bob'})));await assertFails(setDoc(ref(context(),'resolutions','question'),resolution({replyVersion:2})));await assertSucceeds(setDoc(ref(context(),'resolutions','question'),resolution()));});
test('accepted content is immutable until asker reopens',async()=>{const bob=context('bob'),alice=context();await setDoc(ref(bob,'replies','reply'),reply());await setDoc(ref(alice,'resolutions','question'),resolution());await assertFails(updateDoc(ref(bob,'replies','reply'),{body:{...loc(),vi:'Changed'},version:2,updatedAt:serverTimestamp()}));await assertFails(deleteDoc(ref(bob,'replies','reply')));await assertSucceeds(updateDoc(ref(alice,'resolutions','question'),{replyId:'',replyVersion:0,version:2,updatedAt:serverTimestamp()}));await assertSucceeds(deleteDoc(ref(bob,'replies','reply')));});
test('scope changes preserve question and reply identity',async()=>{const alice=context();await setDoc(ref(context('bob'),'replies','reply'),reply());await assertSucceeds(updateDoc(ref(alice,'entries','question'),{requirementId:'',version:2,updatedAt:serverTimestamp()}));await assertSucceeds(getDoc(ref(alice,'replies','reply')));await assertFails(updateDoc(ref(context('bob'),'entries','question'),{requirementId:'FN-BKG-01',version:3,updatedBy:'bob',updatedAt:serverTimestamp()}));});
test('decision requires evidence and a real confirming actor',async()=>{const db=context();await assertSucceeds(setDoc(ref(db,'decisions','decision'),decision()));await assertFails(updateDoc(ref(db,'decisions','decision'),{state:'confirmed',confirmedBy:'alice',confirmedAt:serverTimestamp(),version:2,updatedAt:serverTimestamp()}));await assertFails(updateDoc(ref(db,'decisions','decision'),{state:'confirmed',source:'Approved meeting reference',confirmedBy:'bob',confirmedAt:serverTimestamp(),version:2,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(ref(db,'decisions','decision'),{state:'confirmed',source:'Meeting minute reference',confirmedBy:'alice',confirmedAt:serverTimestamp(),version:2,updatedAt:serverTimestamp()}));});
test('decision creation does not allow fabricated requirements or another author',async()=>{await assertFails(setDoc(ref(context(),'decisions','decision'),decision({requirementIds:['UNKNOWN']})));await assertFails(setDoc(ref(context('bob'),'decisions','decision'),decision({updatedBy:'bob'})));});
test('decision author can supersede while another member cannot edit or delete',async()=>{await setDoc(ref(context(),'decisions','decision'),decision());await assertFails(updateDoc(ref(context('bob'),'decisions','decision'),{state:'superseded',version:2,updatedBy:'bob',updatedAt:serverTimestamp()}));await assertFails(deleteDoc(ref(context(),'decisions','decision')));await assertSucceeds(updateDoc(ref(context(),'decisions','decision'),{state:'superseded',version:2,updatedAt:serverTimestamp()}));});
async function archive(db,id='deleted'){
  const snapshot=(await getDoc(ref(db,'entries','question'))).data();const batch=writeBatch(db);
  batch.set(ref(db,'trash',id),{id,entryId:'question',snapshot,deletedBy:'alice',deletedByName:'Alice',deletedAt:serverTimestamp(),restoredBy:'',restoredAt:null,version:1});batch.delete(ref(db,'entries','question'));await batch.commit();return snapshot;
}
async function restore(db,original,extra={},uid='alice'){
  const batch=writeBatch(db);batch.set(ref(db,'entries','question'),{...original,version:original.version+1,restoredFrom:'deleted',updatedBy:uid,updatedByName:uid,updatedAt:serverTimestamp(),...extra});
  batch.update(ref(db,'trash','deleted'),{restoredBy:uid,restoredAt:serverTimestamp(),version:2});return batch.commit();
}
test('trash snapshot must exactly match the atomically deleted entry',async()=>{const db=context(),snapshot=(await getDoc(ref(db,'entries','question'))).data(),batch=writeBatch(db);batch.set(ref(db,'trash','forged'),{id:'forged',entryId:'question',snapshot:{...snapshot,title:loc('Fake')},deletedBy:'alice',deletedByName:'Alice',deletedAt:serverTimestamp(),restoredBy:'',restoredAt:null,version:1});batch.delete(ref(db,'entries','question'));await assertFails(batch.commit());await assertSucceeds(archive(db));});
test('restoration preserves original content and author and adds a version',async()=>{const db=context(),original=await archive(db);await assertSucceeds(restore(db,original));const result=await getDoc(ref(db,'entries','question'));if(result.data().version!==2||result.data().createdBy!=='alice')throw Error('Provenance changed');});
test('restore cannot inject replacement content, impersonate an owner, or overwrite an existing record',async()=>{const db=context(),original=await archive(db);await assertFails(restore(db,original,{title:loc('Injected')}));await assertFails(restore(context('bob'),original,{},'bob'));await assertSucceeds(restore(db,original));await assertFails(restore(db,original));});
for(const [name,ctx] of [['anonymous',()=>env.unauthenticatedContext().firestore()],['wrong provider',()=>context('alice',{firebase:{sign_in_provider:'google.com'}})],['expired session',()=>context('alice',{auth_time:Math.floor(Date.now()/1000)-90000})]])test(`${name} cannot access new collaboration collections`,async()=>{const db=ctx();for(const type of ['replies','resolutions','decisions','trash'])await assertFails(getDoc(ref(db,type,'anything')));});
