import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Clipboard,Download,LockKeyhole,MessageSquareText,Save,Send} from 'lucide-react';
import {useClientQuestionnaire} from '../lib/useClientQuestionnaire';
import {clientText,clientErrorKey} from '../lib/client-questionnaire-i18n';
import {answerCounts,answerComplete,safeLocalized} from '../../functions/src/questionnaire-model';
import type {AnswerKind,Locale} from '../../functions/src/questionnaire-model';
import {Modal} from '../components/ui';
import i18n from '../lib/i18n';
import './client-questionnaires.css';
export default function ClientRespond(){
  const token=location.pathname.split('/')[2]||'',state=useClientQuestionnaire(token);
  const [language,setLanguage]=useState<Locale>('en'),[name,setName]=useState(''),[email,setEmail]=useState(''),[consent,setConsent]=useState(false);
  const [index,setIndex]=useState(0),[pendingOnly,setPendingOnly]=useState(false),[confirm,setConfirm]=useState(false),[reload,setReload]=useState(false),[message,setMessage]=useState('');
  const defaultApplied=useRef(false),heading=useRef<HTMLHeadingElement>(null),t=clientText(language);
  const q=state.view?.snapshot,questions=q?.questions||[],active=questions[index],response=active?state.answers[active.id]:undefined;
  const answer=response||{kind:'answer' as AnswerKind,text:'',language},counts=answerCounts(state.answers),submitted=state.session?.state==='submitted';
  const readonly=submitted||state.error==='SUBMITTED'||state.view?.state!=='published',validQuestions=questions.filter(v=>!pendingOnly||!answerComplete(state.answers[v.id]));
  useEffect(()=>{if(q&&!defaultApplied.current){defaultApplied.current=true;setLanguage(q.language);}},[q]);
  useEffect(()=>{document.documentElement.lang=language;void i18n.changeLanguage(language);document.title=q?`${q.title} · WeRide`:'WeRide · Client questions';},[language,q?.title]);
  useEffect(()=>{if(state.stage==='response'){heading.current?.focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)heading.current?.scrollIntoView({block:'start',behavior:'instant'});}},[index,state.stage]);
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setMessage(t('cqCopied'));}catch{setMessage(t('cqErrorNETWORK'));}};
  const download=()=>{
    const body=[q?.title||'WeRide responses',`Name: ${state.session?.name||name}`,`Reference: ${state.session?.id||'draft'}`,state.session?.submittedAt||'DRAFT',...questions.flatMap(question=>[`${question.requirementId||'General'} · ${question.id} · v${question.version}`,safeLocalized(question.title,language).text,JSON.stringify(state.answers[question.id]||{status:'not answered'},null,2)])].join('\n\n');
    const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='weride-my-responses.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  const progress=<div className="client-progress"><span>{counts.completed} / {questions.length} {t('cqQuestionCount')}</span><progress max={Math.max(1,questions.length)} value={counts.completed} aria-label={t('cqProgress')}/><small>{counts.answered} {t('cqAnsweredCount')} · {counts.followUp} {t('cqFollowUpCount')}</small></div>;
  return <div className="client-portal"><header className="client-header"><a href={location.pathname} aria-label="WeRide"><span className="client-logo">w</span><strong>weride<small>CLIENT DISCOVERY</small></strong></a><label><span className="sr-only">Language</span><select aria-label="Language" value={language} onChange={e=>{defaultApplied.current=true;setLanguage(e.target.value as Locale);}}><option value="en">English</option><option value="vi">Tiếng Việt</option><option value="sv">Svenska</option></select></label></header>
    <main className="client-main"><div className="client-heading"><span className="eyebrow">MADISON × WERIDE</span><h1>{q?.title||t('cqGuestTitle')}</h1><p>{t('cqGuestIntro')}</p></div>
    {message&&<p className="cq-notice" role="status">{message}</p>}{state.storageLimited&&<p className="cq-notice" role="status">{t('cqBrowserStorage')}</p>}
    {state.error&&<div className="client-error" role="alert"><p>{t(state.error==='CLOSED'?'cqPaused':state.error==='SUBMITTED'?'cqAlreadySubmitted':clientErrorKey(Error(state.error)))}</p>{state.session&&<div className="cq-actions"><button onClick={download} className="button secondary small">{t('cqDownloadDraft')}</button><button className="button secondary small" onClick={()=>setReload(true)}>{t('cqLoadServer')}</button></div>}</div>}
    {state.stage==='loading'&&<p role="status">{t('cqWorking')}</p>}
    {state.stage==='unavailable'&&<section className="client-card"><LockKeyhole size={30}/><h2>{t('cqUnavailable')}</h2></section>}
    {state.stage==='code'&&<section className="client-card client-entry"><LockKeyhole size={28}/><h2>{t('cqUnlock')}</h2><p>{t('cqProtected')}</p><form onSubmit={e=>{e.preventDefault();void state.load(state.code);}}><label className="field"><span>{t('cqCode')}</span><input type="password" autoComplete="off" autoFocus maxLength={64} required value={state.code} onChange={e=>state.setCode(e.target.value)}/></label><button className="button primary" disabled={state.busy}>{t(state.busy?'cqWorking':'cqUnlock')}</button></form></section>}
    {state.view&&state.stage!=='code'&&<section className="client-introduction"><p lang={q?.language}>{q?.introduction}</p><div className="client-deadlines"><span>{questions.length} {t('cqQuestionCount')}</span>{state.view.dueDate&&<span>{t('cqDue')}: {state.view.dueDate}</span>}<span>{t('cqExpires')}: {new Date(state.view.expiresAt).toLocaleString(language)}</span></div></section>}
    {state.stage==='identity'&&state.view?.state==='published'&&<section className="client-card client-entry"><h2>{t('cqStart')}</h2><form onSubmit={e=>{e.preventDefault();void state.start(name,email,language,consent);}}><fieldset disabled={state.busy}><label className="field"><span>{t('cqFullName')}</span><input autoFocus required maxLength={120} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>{t('cqEmail')}</span><input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><p className="cq-notice">{t('cqSafety')}</p><label className="cq-check cq-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t('cqConsent')}</label><button className="button primary" disabled={state.busy||!consent}>{t(state.busy?'cqWorking':'cqStart')}</button></fieldset></form></section>}
    {state.view?.state==='closed'&&<p role="status" className="cq-notice">{t('cqPaused')}</p>}
    {submitted&&<section className="client-card client-receipt"><Check size={30}/><h2>{t('cqThanks')}</h2><p>{t('cqReceipt')}: <strong>{state.session?.id}</strong></p><p>{new Date(state.session!.submittedAt!).toLocaleString(language)}</p><p>{t('cqReceivedNote')}</p><div className="cq-actions"><button className="button secondary" onClick={download}><Download size={16}/>{t('cqDownloadDraft')}</button>{state.view?.state==='published'&&<button className="button secondary" onClick={state.clear}>{t('cqNewResponse')}</button>}</div></section>}
    {state.stage==='response'&&state.session&&<>
      <section className="client-response-summary"><div><strong>{state.session.name}</strong><small>{state.session.email}</small></div>{progress}<div className="cq-actions"><button className="button secondary small" onClick={()=>void copy(state.resumeLink())}><Clipboard size={15}/>{t('cqResume')}</button><button className="button secondary small" onClick={download}><Download size={15}/>{t('cqDownloadDraft')}</button></div><p className="small-note">{t('cqResumeHelp')}</p></section>
      <div className="client-workspace"><nav className="client-question-nav" aria-label={t('cqAllList')}><label className="cq-check"><input type="checkbox" checked={pendingOnly} onChange={e=>setPendingOnly(e.target.checked)}/>{t('cqPendingOnly')}</label><ol>{validQuestions.map(question=>{const n=questions.indexOf(question);return <li key={question.id}><button type="button" aria-current={n===index?'step':undefined} onClick={()=>setIndex(n)}><span className="client-question-number">{answerComplete(state.answers[question.id])?<Check size={15}/>:n+1}</span><span><strong>{question.requirementId||t('cqGeneral')}</strong><small lang={safeLocalized(question.title,language).language}>{safeLocalized(question.title,language).text}</small></span></button></li>;})}</ol></nav>
        {active&&<section className="client-card client-answer-card"><div className="client-question-kicker"><span>{index+1} / {questions.length}</span><strong>{active.requirementId||t('cqGeneral')}</strong></div><h2 ref={heading} tabIndex={-1} lang={safeLocalized(active.title,language).language}>{safeLocalized(active.title,language).text}</h2>
          {safeLocalized(active.title,language).language!==language&&<p className="small-note">{t('cqFallback')}</p>}
          {safeLocalized(active.details,language).text&&<p lang={safeLocalized(active.details,language).language}>{safeLocalized(active.details,language).text}</p>}
          {active.baseline&&<details className="client-baseline"><summary>{t('cqBaselineLabel')}</summary><h3 lang={safeLocalized(active.baseline.title,language).language}>{safeLocalized(active.baseline.title,language).text}</h3><p lang={safeLocalized(active.baseline.description,language).language}>{safeLocalized(active.baseline.description,language).text}</p><small>{q?.sourceReference} · {active.baseline.sourceSection} · p. {active.baseline.sourcePage}</small></details>}
          <fieldset disabled={readonly||state.busy}><div className="form-grid"><label className="field"><span>{t('cqResponseType')}</span><select value={answer.kind} onChange={e=>state.change(active.id,{...answer,kind:e.target.value as AnswerKind})}>{(['answer','clarify','not_applicable','later'] as const).map(kind=><option key={kind} value={kind}>{t(({answer:'cqAnswer',clarify:'cqClarify',not_applicable:'cqNotApplicable',later:'cqLater'})[kind])}</option>)}</select></label>
            <label className="field"><span>{t('cqAnswerLanguage')}</span><select value={answer.language} onChange={e=>state.change(active.id,{...answer,language:e.target.value as Locale})}><option value="en">English</option><option value="vi">Tiếng Việt</option><option value="sv">Svenska</option></select></label></div>
            <label className="field"><span>{t('cqAnswerText')}<small>{answer.text.length}/6000</small></span><textarea lang={answer.language} rows={8} maxLength={6000} value={answer.text} onChange={e=>state.change(active.id,{...answer,text:e.target.value})}/></label>
          </fieldset><div className="client-question-controls"><button className="button secondary" disabled={index===0} onClick={()=>setIndex(n=>n-1)}><ArrowLeft size={16}/>{t('cqPrevious')}</button><button className="button secondary" disabled={index===questions.length-1} onClick={()=>setIndex(n=>n+1)}>{t('cqNext')}<ArrowRight size={16}/></button></div>
        </section>}
      </div>
      {!submitted&&<footer className="client-save-bar"><span role="status" aria-live="polite"><Save size={17}/>{t(state.saving?'cqSaving':state.dirty?'cqUnsaved':'cqSaved')}{!state.dirty&&state.session.savedAt&&<small>{new Date(state.session.savedAt).toLocaleTimeString(language)}</small>}</span><div className="cq-actions"><button className="button secondary" disabled={state.busy||state.saving||readonly||state.error==='CONFLICT'} onClick={()=>void state.flush().catch(()=>{})}>{t('cqSaveNow')}</button><button className="button primary" disabled={state.busy||state.saving||readonly||counts.completed===0||state.error==='CONFLICT'} onClick={()=>setConfirm(true)}><Send size={16}/>{t('cqReviewSubmit')}</button></div></footer>}
    </>}
    <p className="client-footnote"><MessageSquareText size={16}/>{t('cqSafety')}</p></main>
    {confirm&&<Modal title={t('cqSubmitTitle')} onClose={()=>{if(!state.busy)setConfirm(false);}}><div className="modal-body"><p>{t('cqSubmitHelp')}</p><p>{counts.answered} {t('cqAnsweredCount')} · {counts.followUp} {t('cqFollowUpCount')} · {questions.length-counts.completed} {t('cqBlankCount')}</p>{state.error&&<p role="alert" className="error-banner">{t(clientErrorKey(Error(state.error)))}</p>}</div><footer className="modal-footer"><button className="button secondary" disabled={state.busy} onClick={()=>setConfirm(false)}>{t('cqCancel')}</button><button className="button primary" disabled={state.busy} onClick={()=>void state.submit().then(()=>setConfirm(false)).catch(()=>{})}>{t(state.busy?'cqWorking':'cqSubmit')}</button></footer></Modal>}
    {reload&&<Modal title={t('cqLoadServer')} onClose={()=>setReload(false)}><div className="modal-body"><p>{t('cqLoadWarning')}</p><button className="button secondary" onClick={download}>{t('cqDownloadDraft')}</button></div><footer className="modal-footer"><button className="button secondary" onClick={()=>setReload(false)}>{t('cqCancel')}</button><button className="button primary" disabled={state.busy||state.saving} onClick={()=>void state.reloadServer().then(()=>setReload(false))}>{t('cqLoadServer')}</button></footer></Modal>}
  </div>;
}
