import { useEffect, useRef, useState } from 'react';
import RequirementsTable from '../components/RequirementsTable';
import { useAuth } from '../lib/auth';
import { filterByPic, memberLabel } from '../lib/assignment';
import ReviewPackButton from '../components/ReviewPackButton';
import { useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Braces, ChevronDown, Download, Filter, Search, X } from 'lucide-react';
import { useWorkspace } from '../lib/store';
import { filterRequirements, download, matrixCsv } from '../lib/helpers';
import { Badge } from '../components/ui';
export default function Matrix(){
  const {data}=useWorkspace();const {member}=useAuth();const d=data!;const {t,i18n}=useTranslation();const [params,setParams]=useSearchParams(),[exports,setExports]=useState(false);
  const sort=params.get('sort')==='id';const exportRoot=useRef<HTMLDivElement>(null),exportButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!exports)return;const outside=(e:Event)=>{if(!exportRoot.current?.contains(e.target as Node))setExports(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setExports(false);exportButton.current?.focus();}};const frame=requestAnimationFrame(()=>exportRoot.current?.querySelector<HTMLButtonElement>('.export-menu button')?.focus());document.addEventListener('pointerdown',outside);document.addEventListener('focusin',outside);document.addEventListener('keydown',key);return()=>{cancelAnimationFrame(frame);document.removeEventListener('pointerdown',outside);document.removeEventListener('focusin',outside);document.removeEventListener('keydown',key);};},[exports]);
  const q=params.get('q')||'',module=params.get('module')||'',tier=params.get('tier')||'',state=params.get('state')||'',compliance=params.get('compliance')||'',pic=params.get('pic')||'';
  const update=(key:string,value:string)=>{const next=new URLSearchParams(window.location.search);if(value)next.set(key,value);else next.delete(key);setParams(next,{replace:true});};
  const filtered=filterRequirements(d.requirements,d.entries,d.reviews,q,module,tier,state,compliance,i18n.language);const scoped= params.get('missing')==='response'?filtered.filter(r=>!d.reviews.some(v=>v.id===r.id&&v.compliance)):filtered;const selected=filterByPic(scoped,d.assignments||[],pic,member?.uid||'');const rows=sort?[...selected].sort((a,b)=>a.id.localeCompare(b.id)):selected;
  return <div className="page-enter"><div className="page-heading matrix-page-heading"><div><span className="eyebrow">RFP / SECTION 03</span><h1>{t('matrixTitle')}</h1><p>{t('matrixSubtitle')}</p></div><div className="ai-page-actions"><ReviewPackButton module={module}/><div ref={exportRoot} className="export-control"><button ref={exportButton} aria-controls="matrix-export-menu" className="button secondary" onClick={()=>setExports(!exports)} aria-expanded={exports}><Download size={16}/>{t('export')}<ChevronDown size={14}/></button>{exports&&<div id="matrix-export-menu" className="export-menu" role="group" aria-label={t('export')}><button onClick={()=>{download('weride-matrix.csv',matrixCsv(rows,d,i18n.language),'text/csv;charset=utf-8');setExports(false);}}><Download size={15}/>{t('exportCsv')}</button><button onClick={()=>{download('weride-workspace.json',JSON.stringify({...d,exportedAt:new Date().toISOString()},null,2),'application/json');setExports(false);}}><Braces size={15}/>{t('exportJson')}</button><p>{t('exportNote')}</p></div>}</div></div></div>
    <div className="matrix-summary">{['A','B','C'].map(m=><button className={module===m?'selected':''} key={m} onClick={()=>update('module',module===m?'':m)}><span className={`module-dot dot-${m}`}/><strong>{t('module'+m)}</strong><Badge>{d.requirements.filter(r=>r.module===m).length}</Badge></button>)}</div>
    <section className="matrix-panel"><div className="matrix-toolbar"><label className="search-field"><Search size={17}/><input aria-label={t('searchLabel')} placeholder={t('search')} value={q} onChange={e=>update('q',e.target.value)}/>{q&&<button onClick={()=>update('q','')} aria-label={t('resetFilters')}><X size={14}/></button>}</label><div className="matrix-filters"><Filter size={16}/><select aria-label={t('picFilter')} value={pic} onChange={e=>update('pic',e.target.value)}><option value="">{t('picAll')}</option><option value="mine">{t('picMine')}</option><option value="unassigned">{t('picUnassigned')}</option>{[...(d.members||[])].sort((a,b)=>memberLabel(a).localeCompare(memberLabel(b))).map(p=><option key={p.uid} value={`uid:${p.uid}`}>{memberLabel(p)}{!p.active?` · ${t('picInactive')}`:''}</option>)}</select><select aria-label={t('allModules')} value={module} onChange={e=>update('module',e.target.value)}><option value="">{t('allModules')}</option>{['A','B','C'].map(m=><option key={m} value={m}>Module {m}</option>)}</select><select aria-label={t('allTiers')} value={tier} onChange={e=>update('tier',e.target.value)}><option value="">{t('allTiers')}</option><option>L1</option><option>L2</option></select><select aria-label={t('allStatuses')} value={state} onChange={e=>update('state',e.target.value)}><option value="">{t('allStatuses')}</option>{['unreviewed','reviewing','clarified','scoped'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select><select aria-label={t('allCompliance')} value={compliance} onChange={e=>update('compliance',e.target.value)}><option value="">{t('allCompliance')}</option><option value="unassessed">{t('unassessed')}</option>{['FC','PC','RD','CU','NC'].map(c=><option key={c} value={c}>{t(c)}</option>)}</select></div></div>
    <RequirementsTable rows={rows} onSort={()=>update('sort',sort?'':'id')} sorted={sort}/><div className="table-footer"><span role="status" aria-live="polite">{t('showing',{count:rows.length,total:d.requirements.length})}</span>{(q||module||tier||state||compliance||pic||params.get('missing'))&&<button onClick={()=>setParams(params.has('preview')?{preview:'1'}:{})}>{t('resetFilters')}<X size={13}/></button>}<span className="table-source">{t('sourceReadOnly')}</span></div></section>
    {params.get('missing')==='response'&&<p className="small-note">{t('uxMissingResponse')}</p>}<p className="source-footnote">{t('blankCompliance')}</p>
  </div>;
}
