import {useAuth} from '../lib/auth';
import {effectiveQuestionStatus,scopedCount} from '../lib/collaboration';
import { activityTarget } from '../lib/question-hub';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Box, CalendarDays, CheckCheck, ChevronRight, CircleHelp, Layers3, ListChecks, MessageSquareText, ShieldCheck, Sparkles } from 'lucide-react';
import { useWorkspace } from '../lib/store';
import { text, formatDate } from '../lib/i18n';
import { Badge } from '../components/ui';
export default function Overview(){
  const {data}=useWorkspace();const {member}=useAuth();const {t,i18n}=useTranslation();const d=data!;
  const reviewed=scopedCount(d);const percent=d.requirements.length?Math.round(reviewed/d.requirements.length*100):0;
  const work=[{key:'uxMyPic',count:(d.assignments||[]).filter(a=>a.assigneeUid===member?.uid).length,path:'/requirements?pic=mine'},{key:'uxUrgent',count:d.entries.filter(e=>e.kind==='qa'&&effectiveQuestionStatus(e,d)==='open'&&['high','critical'].includes(e.priority)).length,path:'/questions?status=open&priority=urgent&sort=priority'},{key:'uxMissingResponse',count:d.requirements.filter(r=>!d.reviews.some(v=>v.id===r.id&&v.compliance)).length,path:'/requirements?missing=response'},{key:'uxUnvalidated',count:d.entries.filter(e=>e.kind==='assumption'&&e.status==='unvalidated').length,path:'/search?type=assumption&status=unvalidated'}];
  const modules=[{id:'A',icon:Box,subtitle:'moduleADesc'},{id:'B',icon:ShieldCheck,subtitle:'moduleBDesc'},{id:'C',icon:Sparkles,subtitle:'moduleCDesc'}];
  return <div className="page-enter"><div className="page-heading"><div><span className="eyebrow">{t('rfpWorkspace')}</span><h1>{t('greeting')}</h1></div><Badge tone="green">{d.project.client}</Badge></div>
    <section className="my-work"><h2>{t('uxMyWork')}</h2><p>{t('uxMyWorkHint')}</p><div className="my-work-grid">{work.map(w=><Link key={w.key} to={w.path}><span>{t(w.key)}</span><strong>{w.count}</strong></Link>)}</div><div className="progress-stages">{['unreviewed','reviewing','clarified','scoped'].map(state=><Link key={state} to={`/requirements?state=${state}`}>{t(state)} · {d.requirements.filter(r=>(d.reviews.find(v=>v.id===r.id)?.state||'unreviewed')===state).length}</Link>)}</div><small>{t('uxProgressHint')}</small></section><section className="hero"><div className="hero-copy"><div className="hero-kicker"><span/> {d.project.reference}</div><h2>WeRide.<br/><span>{t('workspace')}</span></h2><p>{text(d.project.summary,i18n.language)}</p><div className="hero-actions"><Link className="button lime" to="/requirements">{t('openMatrix')}<ArrowUpRight size={17}/></Link><Link className="hero-link" to="/system">{t('viewSystem')}<ArrowRight size={16}/></Link></div></div><div className="hero-visual" aria-hidden="true"><svg viewBox="0 0 460 280"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="currentColor" strokeWidth=".5"/></pattern></defs><rect width="460" height="280" fill="url(#grid)"/><path className="map-road" d="M-20 196L98 95L205 180L320 77L490 210M-20 77L97 184L218 75L342 179L483 74M75-20L74 310M219-20L219 310M363-20L363 310"/><path className="map-route" d="M74 184L99 163L150 207L219 147L255 179L320 122L363 160"/><circle className="map-halo" cx="74" cy="184" r="24"/><circle className="map-pin" cx="74" cy="184" r="6"/><circle className="map-halo" cx="363" cy="160" r="24"/><circle className="map-pin" cx="363" cy="160" r="6"/><g transform="translate(197 126)"><rect width="44" height="44" rx="13" fill="#c1f7a9"/><path d="m10 27 12-17 12 17-12-5Z" fill="#17302a"/></g></svg><div className="map-label map-label-start"><span>L1</span>{t('l1Requirements').split('·')[1]}</div><div className="map-label map-label-end"><span>L2</span>{t('l2Requirements').split('·')[1]}<ArrowDownRight size={14}/></div><div className="hero-visual-bottom"><i/><span>{t('uxProgress')}</span><strong>{percent}%</strong></div></div></section>
    <section className="stats-grid">{[
      {label:'totalRequirements',value:d.requirements.length,note:'requirementNote',icon:ListChecks,path:'/requirements'},
      {label:'l1Requirements',value:d.requirements.filter(r=>r.tier==='L1').length,note:'l1Note',icon:Layers3,path:'/requirements?tier=L1'},
      {label:'l2Requirements',value:d.requirements.filter(r=>r.tier==='L2').length,note:'l2Note',icon:Sparkles,path:'/requirements?tier=L2'},
      {label:'openQuestions',value:d.entries.filter(e=>e.kind==='qa'&&effectiveQuestionStatus(e,d)==='open').length,note:'questionNote',icon:MessageSquareText,path:'/questions?status=open'},
    ].map(({label,value,note,icon:Icon,path})=><Link key={label} className="stat-card" to={path}><div className="stat-top"><span>{t(label)}</span><Icon size={18}/></div><strong>{value.toString().padStart(2,'0')}</strong><p>{t(note)}</p></Link>)}</section>
    <div className="section-heading"><h2>{t('modules')}</h2><Link to="/requirements">{t('matrix')}<ArrowRight size={15}/></Link></div><section className="module-grid">{modules.map(({id,icon:Icon,subtitle})=>{const reqs=d.requirements.filter(r=>r.module===id);const count=d.reviews.filter(rev=>rev.state==='scoped'&&reqs.some(r=>r.id===rev.id)).length;return <Link className={`module-card module-${id}`} to={`/requirements?module=${id}`} key={id}><div className="module-top"><span className="module-icon"><Icon size={21}/></span><Badge tone={id==='C'?'purple':'green'}>{id==='C'?'L2':'L1'}</Badge></div><span className="eyebrow">MODULE {id}</span><h3>{t('module'+id)}</h3><p>{t(subtitle)}</p><div className="module-progress"><span style={{width:`${count/reqs.length*100}%`}}/></div><div className="module-footer"><strong>{reqs.length} {t('requirements')}</strong><span>{count}/{reqs.length} {t('reviewed')}<ArrowUpRight size={15}/></span></div></Link>;})}</section>
    <section className="dashboard-bottom"><div className="panel timeline-panel"><div className="section-heading"><h2><CalendarDays size={18}/>{t('timeline')}</h2><Badge>2026</Badge></div><div className="timeline">{d.project.milestones.map((m,index)=><div className={`milestone ${index===0?'milestone-first':''}`} key={m.key}><div className="milestone-line"><span>{index===0?<CheckCheck size={12}/>:index+1}</span></div><div className="milestone-copy"><strong>{t(m.key)}</strong><span>{formatDate(m.date,i18n.language)}{m.time&&<small>{m.time}</small>}</span></div></div>)}</div><p className="small-note">{t('coverDates')}</p></div><div className="dashboard-side"><Link to="/sources" className="clarification-card"><span className="clarification-icon"><CircleHelp size={23}/></span><div><span className="eyebrow">{t('attention')}</span><h3>{text(d.project.clarifications[0].title,i18n.language)}</h3><p>{text(d.project.clarifications[0].body,i18n.language)}</p></div><ArrowUpRight size={18}/></Link><div className="panel readiness-panel"><div className="section-heading"><h2>{t('uxProgress')}</h2><span className="readiness-number">{percent}<small>%</small></span></div><div className="progress-track"><span style={{width:`${percent}%`}}/></div><p>{reviewed} / {d.requirements.length} {t('reviewed')}</p><small>{t('uxProgressHint')}</small></div></div></section>
    <section className="panel activity-preview"><div className="section-heading"><h2>{t('latestActivity')}</h2><Link to="/activity">{t('allActivity')}<ChevronRight size={16}/></Link></div>{d.activities.length?d.activities.slice(0,3).map(e=><Link className="mini-activity" to={activityTarget(e)} key={e.id}><span className="avatar small">{e.actorName[0]}</span><span><strong>{e.actorName}</strong> · {t(e.action==='delete'?'deletedAction':e.action)}<small>{e.requirementId||t('qhGeneral')} · {text(e.title,i18n.language)}</small></span><time>{formatDate(e.at,i18n.language,true)}</time></Link>):<div className="empty-inline"><MessageSquareText size={22}/>{t('noActivity')}</div>}</section>
  </div>;
}
