"""Rebuild the PRIVATE source fixture. English matrix wording is transcribed from RFP §3.
Vietnamese/Swedish translations and discovery work items are Madison working drafts.
This file and private/seed.json must never be shipped as Hosting assets.
"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent

def tr(s):
    p=s.split('|||')
    assert len(p)==3, s
    return dict(zip(['en','vi','sv'], (v.strip() for v in p)))
rows=[]
def req(id, module, page, title, desc, question, tasks, assumption):
    rows.append(dict(id=id,module=module,tier='L2' if module=='C' else 'L1',sourcePage=page,sourceSection='3',title=tr(title),description=tr(desc),question=tr(question),tasks=[tr(t) for t in tasks],assumption=tr(assumption)))

req('FN-BKG-01','A',6,
'Multi-Channel Booking Intake|||Tiếp nhận đặt xe đa kênh|||Bokningsmottagning via flera kanaler',
'Support ride requests from mobile apps, web dispatch console, hotel portals, and partner (OTA) APIs.|||Hỗ trợ yêu cầu đặt xe từ ứng dụng di động, bảng điều phối web, cổng khách sạn và API đối tác (OTA).|||Stöd för resebeställningar från mobilappar, webbaserad trafikledning, hotellportaler och partner-API:er (OTA).',
'Which booking channels and OTA partners must be available at L1 launch, and who owns their API access?|||Kênh đặt xe và đối tác OTA nào bắt buộc ở L1, và ai chịu trách nhiệm cấp quyền API?|||Vilka bokningskanaler och OTA-partner krävs vid L1-lanseringen, och vem ansvarar för API-åtkomst?',
['Define a shared booking model and lifecycle|||Định nghĩa mô hình và vòng đời đặt xe chung|||Definiera gemensam bokningsmodell och livscykel','Implement channel adapters and duplicate protection|||Xây dựng bộ kết nối từng kênh và chống trùng lặp|||Implementera kanaladaptrar och dubblettskydd','Test creation, cancellation and channel attribution|||Kiểm thử tạo, huỷ và ghi nhận kênh đặt xe|||Testa skapande, avbokning och kanalspårning'],
'Launch integrations will be agreed individually; partner API access and sandbox availability remain unconfirmed.|||Từng tích hợp triển khai sẽ được thống nhất riêng; quyền API và môi trường thử nghiệm đối tác chưa được xác nhận.|||Lanseringsintegrationer avtalas var för sig; API-åtkomst och partnernas testmiljöer är ännu inte bekräftade.')
req('FN-BKG-02','A',6,
'Dynamic Upfront Fare Calculation|||Tính giá trước chuyến đi linh hoạt|||Dynamisk beräkning av förhandspris',
'Upfront pricing engine supporting base rates, distance/time pricing, zone rates, and surge multipliers.|||Bộ máy tính giá trước chuyến đi hỗ trợ giá cơ bản, theo quãng đường/thời gian, theo vùng và hệ số tăng giá.|||Motor för förhandspriser med grundpris, avstånds-/tidspris, zonpriser och efterfrågemultiplikatorer.',
'How are fare rules, minimum fares, rounding, waiting time and surge limits approved?|||Quy tắc giá, giá tối thiểu, làm tròn, thời gian chờ và giới hạn tăng giá được phê duyệt thế nào?|||Hur godkänns prisregler, minimipriser, avrundning, väntetid och gränser för pristillägg?',
['Model versioned fare rules and service zones|||Mô hình hoá quy tắc giá có phiên bản và vùng dịch vụ|||Modellera versionshanterade prisregler och servicezoner','Build quote calculation and quote validity|||Xây dựng tính giá và thời hạn hiệu lực báo giá|||Bygg prisberäkning och giltighetstid för offerter','Validate fare scenarios and booking price snapshots|||Xác thực kịch bản giá và lưu giá tại thời điểm đặt|||Validera prisscenarier och sparade bokningspriser'],
'Weride will approve fare tables and edge-case policies before implementation estimates are finalized.|||Weride sẽ duyệt bảng giá và chính sách ngoại lệ trước khi chốt ước lượng triển khai.|||Weride godkänner pristabeller och undantagsregler innan implementeringsestimat fastställs.')
req('FN-DIS-01','A',6,
'Automated & Dynamic Dispatching|||Điều phối tự động và linh hoạt|||Automatiserad och dynamisk trafikledning',
'Algorithmic driver matching based on driver proximity, vehicle class, and zone queue position.|||Ghép tài xế bằng thuật toán theo khoảng cách, hạng xe và vị trí trong hàng đợi vùng.|||Algoritmisk förarmatchning baserad på närhet, fordonsklass och köposition inom zonen.',
'What are the dispatch ranking rules, offer timeouts, re-offer rules and manual override priorities?|||Quy tắc xếp hạng, thời hạn nhận chuyến, mời lại và ưu tiên ghi đè thủ công là gì?|||Vilka regler gäller för rangordning, svarstid, nya erbjudanden och manuell prioritering?',
['Specify matching rules and zone queues|||Đặc tả quy tắc ghép chuyến và hàng đợi vùng|||Specificera matchningsregler och zonköer','Implement offers, timeout and reassignment|||Xây dựng mời chuyến, hết hạn và phân công lại|||Implementera erbjudanden, tidsgränser och omfördelning','Simulate dispatch fairness and failure scenarios|||Mô phỏng công bằng điều phối và tình huống lỗi|||Simulera rättvis fördelning och felscenarier'],
'A transparent rules-based L1 matcher is proposed; machine-learning optimization is not assumed.|||Đề xuất bộ ghép chuyến L1 dựa trên quy tắc minh bạch; không mặc định có tối ưu học máy.|||En transparent regelbaserad L1-matchare föreslås; maskininlärningsoptimering förutsätts inte.')
req('FN-DIS-02','A',6,
'Live Dispatch Console & Map View|||Bảng điều phối trực tiếp và bản đồ|||Trafikledningskonsol och karta i realtid',
'Real-time map rendering active vehicles, trip statuses, and manual dispatcher override capabilities. Trip logs with arrival/finished time and lat/lon position.|||Bản đồ thời gian thực hiển thị xe hoạt động, trạng thái chuyến và khả năng ghi đè thủ công của điều phối viên. Nhật ký chuyến có giờ đến/kết thúc và vị trí vĩ độ/kinh độ.|||Realtidskarta över aktiva fordon, resestatus och möjlighet till manuell omstyrning. Reseloggar med ankomst-/sluttid och latitud/longitud.',
'What fleet scale, location refresh interval and historical trip retention should the console support?|||Bảng điều phối cần hỗ trợ bao nhiêu xe, tần suất cập nhật vị trí và thời gian lưu lịch sử nào?|||Vilken flottstorlek, uppdateringsfrekvens och lagringstid för reshistorik ska konsolen stödja?',
['Build map, vehicle filters and trip board|||Xây dựng bản đồ, lọc xe và bảng chuyến|||Bygg karta, fordonsfilter och resetavla','Implement safe manual assignment and overrides|||Triển khai phân công và ghi đè thủ công an toàn|||Implementera säker manuell tilldelning och omstyrning','Capture arrival, completion and GPS event history|||Ghi lịch sử đến nơi, hoàn thành và sự kiện GPS|||Registrera ankomst, slutförande och GPS-historik'],
'The RFP reference case of 150 vehicles is illustrative, not a confirmed production fleet size.|||Trường hợp tham chiếu 150 xe trong RFP là minh hoạ, không phải quy mô vận hành đã xác nhận.|||RFP-exemplet med 150 fordon är illustrativt, inte en bekräftad produktionsflotta.')
req('FN-DRV-01','A',6,
'Driver Mobile Application|||Ứng dụng di động tài xế|||Mobilapp för förare',
'Native/cross-platform app featuring trip offer cards (marketplace), execution workflow, and earnings summaries.|||Ứng dụng native/đa nền tảng có thẻ mời chuyến (marketplace), quy trình thực hiện chuyến và tổng hợp thu nhập.|||Inbyggd/plattformsöverskridande app med reserbjudanden (marknadsplats), arbetsflöde och intäktsöversikter.',
'Which driver devices, OS versions, onboarding checks and poor-connectivity behaviors are required?|||Thiết bị, phiên bản hệ điều hành, kiểm tra đăng ký và hành vi khi mạng yếu nào bắt buộc cho tài xế?|||Vilka enheter, OS-versioner, introduktionskontroller och beteenden vid svag uppkoppling krävs?',
['Design offer cards and trip state transitions|||Thiết kế thẻ mời chuyến và chuyển trạng thái|||Utforma erbjudandekort och tillståndsövergångar','Implement driver workflow and earnings views|||Triển khai quy trình tài xế và màn hình thu nhập|||Implementera förarflöde och intäktsvyer','Test permissions, network recovery and releases|||Kiểm thử quyền, khôi phục kết nối và phát hành|||Testa behörigheter, nätverksåterhämtning och releaser'],
'App-store accounts, supported devices and operational acceptance criteria must be confirmed by Weride.|||Weride cần xác nhận tài khoản kho ứng dụng, thiết bị hỗ trợ và tiêu chí nghiệm thu vận hành.|||Weride behöver bekräfta appbutikskonton, enhetsstöd och operativa acceptanskriterier.')
req('FN-DRV-02','A',6,
'Navigation Handoff|||Chuyển tiếp điều hướng|||Överlämning till navigering',
'Direct one-tap handoff from driver app to external/built in navigation.|||Chuyển tiếp một chạm từ ứng dụng tài xế sang điều hướng bên ngoài/tích hợp.|||Direkt överlämning med ett tryck från förarappen till extern/inbyggd navigering.',
'Is external navigation handoff sufficient for L1, or is embedded turn-by-turn navigation mandatory?|||Chuyển sang ứng dụng điều hướng ngoài có đủ cho L1, hay bắt buộc điều hướng từng chặng tích hợp?|||Räcker överlämning till extern navigering för L1, eller krävs inbyggd sväng-för-sväng-navigering?',
['Confirm navigation providers and supported platforms|||Xác nhận nhà cung cấp điều hướng và nền tảng|||Bekräfta navigeringsleverantörer och plattformar','Implement destination deep links and fallback|||Triển khai liên kết sâu đến điểm đến và dự phòng|||Implementera djuplänkar till destination och reservflöde','Test pickup and drop-off handoff on devices|||Kiểm thử chuyển điều hướng điểm đón/trả trên thiết bị|||Testa navigering till hämtning och lämning på enheter'],
'External navigation is a proposed implementation option, not an agreed exclusion of embedded navigation.|||Điều hướng ngoài là phương án đề xuất, không phải loại trừ đã thống nhất đối với điều hướng tích hợp.|||Extern navigering är ett föreslaget alternativ, inte en överenskommen uteslutning av inbyggd navigering.')
req('FN-PAS-01','A',6,
'Passenger Mobile App|||Ứng dụng di động hành khách|||Mobilapp för passagerare',
'Native/cross-platform app supporting instant/advance bookings, live ETA tracking, and driver/vehicle details.|||Ứng dụng native/đa nền tảng hỗ trợ đặt ngay/đặt trước, theo dõi ETA trực tiếp và thông tin tài xế/xe.|||Inbyggd/plattformsöverskridande app för direkt- och förhandsbokning, ETA-spårning i realtid samt förar-/fordonsuppgifter.',
'What passenger registration, cancellation, no-show and scheduled-ride rules apply at launch?|||Quy tắc đăng ký, huỷ chuyến, khách không đến và đặt trước nào áp dụng khi ra mắt?|||Vilka regler gäller för registrering, avbokning, utebliven passagerare och förbokade resor vid lansering?',
['Design passenger booking and scheduled-ride flows|||Thiết kế luồng đặt xe và đặt trước cho hành khách|||Utforma bokningsflöden och förbokade resor','Implement live ETA and driver/vehicle information|||Triển khai ETA trực tiếp và thông tin tài xế/xe|||Implementera ETA i realtid och förar-/fordonsuppgifter','Test booking lifecycle and store submissions|||Kiểm thử vòng đời đặt xe và gửi duyệt ứng dụng|||Testa bokningslivscykel och appbutiksinlämningar'],
'Passenger app delivery remains part of L1 as stated in the RFP; adoption assumptions require discovery.|||Ứng dụng hành khách vẫn thuộc L1 theo RFP; giả định về mức sử dụng cần discovery.|||Passagerarappen ingår i L1 enligt RFP:n; antaganden om användning kräver vidare analys.')
req('FN-PAS-02','A',7,
'Swedish Digital Payments|||Thanh toán số tại Thụy Điển|||Svenska digitala betalningar',
'In-app credit/debit card tokenization (Stripe/Adyen) and native Swedish Swish e-commerce payment API.|||Token hoá thẻ tín dụng/ghi nợ trong ứng dụng (Stripe/Adyen) và API thanh toán thương mại điện tử Swish của Thụy Điển.|||Tokenisering av kredit-/betalkort i appen (Stripe/Adyen) och det svenska Swish-API:et för e-handel.',
'Which payment provider, merchant-of-record model, Swish agreement and refund flows are approved?|||Nhà cung cấp thanh toán, mô hình bên thu tiền, hợp đồng Swish và quy trình hoàn tiền nào được duyệt?|||Vilken betalningsleverantör, betalningsansvarig part, Swish-överenskommelse och återbetalningsflöden är godkända?',
['Confirm merchant onboarding and payment contracts|||Xác nhận đăng ký đơn vị bán hàng và hợp đồng thanh toán|||Bekräfta handlarregistrering och betalningsavtal','Implement card tokens, Swish and verified webhooks|||Triển khai token thẻ, Swish và webhook đã xác thực|||Implementera korttoken, Swish och verifierade webhooks','Test reconciliation, refunds and duplicate events|||Kiểm thử đối soát, hoàn tiền và sự kiện trùng|||Testa avstämning, återbetalning och dubbletthändelser'],
'Payment accounts, Swish certificates and transaction fees are external dependencies to be confirmed.|||Tài khoản thanh toán, chứng thư Swish và phí giao dịch là phụ thuộc bên ngoài cần xác nhận.|||Betalningskonton, Swish-certifikat och transaktionsavgifter är externa beroenden som måste bekräftas.')
req('FN-COM-01','A',7,
'In-App Messaging & Masked Calling|||Nhắn tin trong ứng dụng và gọi ẩn số|||Meddelanden i appen och maskerade samtal',
'Centralized cross-platform text messaging and proxy phone number masking between rider, driver, and dispatcher.|||Nhắn tin văn bản tập trung đa nền tảng và che số điện thoại qua số trung gian giữa hành khách, tài xế và điều phối viên.|||Centraliserade textmeddelanden över plattformar och maskering av telefonnummer via proxy mellan passagerare, förare och trafikledare.',
'Who may read conversation history, how long is it retained, and which telephony provider supports Swedish numbers?|||Ai được đọc lịch sử trò chuyện, lưu bao lâu và nhà cung cấp thoại nào hỗ trợ số Thụy Điển?|||Vem får läsa konversationshistorik, hur länge sparas den och vilken telefonileverantör stöder svenska nummer?',
['Model trip-scoped conversations and permissions|||Mô hình hoá hội thoại theo chuyến và quyền truy cập|||Modellera resebundna konversationer och behörigheter','Implement messaging and masked-call integration|||Triển khai nhắn tin và tích hợp gọi ẩn số|||Implementera meddelanden och maskerade samtal','Test retention, access control and support retrieval|||Kiểm thử lưu trữ, phân quyền và tra cứu hỗ trợ|||Testa lagring, åtkomstkontroll och supportåtkomst'],
'Communication history ownership and retention are unconfirmed and must be explicitly agreed.|||Quyền sở hữu và thời gian lưu lịch sử liên lạc chưa được xác nhận, cần thống nhất rõ.|||Ägande och lagringstid för kommunikationshistorik är obekräftade och måste avtalas uttryckligen.')
req('FN-HTL-01','A',7,
'Hotel Concierge Portal|||Cổng lễ tân khách sạn|||Hotellportal för concierge',
'Simplified web portal for hotel/corporate staff to order guest rides, track ETAs, and charge to room or corporate accounts.|||Cổng web đơn giản cho nhân viên khách sạn/doanh nghiệp đặt xe cho khách, theo dõi ETA và tính phí vào phòng hoặc tài khoản doanh nghiệp.|||Förenklad webbportal för hotell-/företagspersonal att beställa gästresor, följa ETA och debitera rum eller företagskonton.',
'How should room charging, hotel credit limits, corporate billing and staff access work?|||Tính phí vào phòng, hạn mức khách sạn, thanh toán doanh nghiệp và quyền nhân viên cần vận hành thế nào?|||Hur ska rumsdebitering, hotellkreditgränser, företagsfakturering och personalåtkomst fungera?',
['Define hotel tenancy and receptionist permissions|||Định nghĩa phân tách khách sạn và quyền lễ tân|||Definiera hotellisolering och receptionsbehörigheter','Build guest booking and ETA management|||Xây dựng đặt xe cho khách và quản lý ETA|||Bygg gästbokning och ETA-hantering','Validate room/account charging and reporting|||Xác thực tính phí phòng/tài khoản và báo cáo|||Validera rums-/kontodebitering och rapportering'],
'PMS integration is not explicitly specified in the matrix and must not be assumed included or excluded.|||Tích hợp PMS không được mô tả rõ trong matrix; không mặc định bao gồm hay loại trừ.|||PMS-integration specificeras inte uttryckligen i matrisen och får inte antas ingå eller vara utesluten.')
req('FN-SUP-01','A',7,
'Fleet Carrier Portal|||Cổng đối tác đội xe|||Portal för åkerier',
'Web portal for third-party fleet owners (carriers) to manage sub-fleets, driver documentation, and payouts.|||Cổng web cho chủ đội xe bên thứ ba quản lý đội xe con, hồ sơ tài xế và chi trả.|||Webbportal för externa flottägare (åkerier) för hantering av underflottor, förardokumentation och utbetalningar.',
'What carrier hierarchy, document approval process and payout calculation model are required?|||Cần cấu trúc đối tác, quy trình duyệt hồ sơ và mô hình tính chi trả nào?|||Vilken åkerihierarki, dokumentgranskning och modell för utbetalningsberäkning krävs?',
['Model carrier organizations and fleet permissions|||Mô hình hoá tổ chức đối tác và quyền đội xe|||Modellera åkeriorganisationer och flottbehörigheter','Build driver/vehicle document management|||Xây dựng quản lý hồ sơ tài xế/xe|||Bygg dokumenthantering för förare och fordon','Implement payout statements and reconciliation views|||Triển khai sao kê chi trả và màn hình đối soát|||Implementera utbetalningsbesked och avstämningsvyer'],
'Carrier payout frequency, approval roles and banking integration boundaries remain to be confirmed.|||Tần suất chi trả, vai trò phê duyệt và phạm vi tích hợp ngân hàng cần được xác nhận.|||Utbetalningsfrekvens, godkännanderoller och gränser för bankintegration återstår att bekräfta.')
req('FN-VOU-01','A',7,
'Voucher & Promotion Engine|||Bộ máy voucher và khuyến mãi|||Motor för kuponger och kampanjer',
'Admin tool to generate discount vouchers and promo codes with checkout redemption in the passenger app.|||Công cụ quản trị tạo voucher giảm giá và mã khuyến mãi để sử dụng khi thanh toán trong ứng dụng hành khách.|||Administrationsverktyg för rabattkuponger och kampanjkoder som löses in i passagerarappens kassa.',
'What voucher eligibility, stacking, redemption limits, expiry and refund rules are needed?|||Cần quy tắc điều kiện, cộng dồn, giới hạn sử dụng, hết hạn và hoàn tiền voucher nào?|||Vilka regler krävs för behörighet, kombination, inlösengränser, giltighet och återbetalning?',
['Define campaign rules and eligibility conditions|||Định nghĩa quy tắc chiến dịch và điều kiện áp dụng|||Definiera kampanjregler och behörighetsvillkor','Build voucher issuance and checkout redemption|||Xây dựng phát hành voucher và áp dụng khi thanh toán|||Bygg kupongutfärdande och inlösen i kassan','Test usage limits and concurrent redemptions|||Kiểm thử giới hạn và sử dụng đồng thời|||Testa användningsgränser och samtidig inlösen'],
'Promotions in L1 are distinct from the L2 points/subscription economy; final rules need approval.|||Khuyến mãi L1 tách biệt hệ điểm/gói đăng ký L2; quy tắc cuối cần được duyệt.|||L1-kampanjer är separata från L2:s poäng-/prenumerationsekonomi; slutregler måste godkännas.')
req('FN-INT-01','A',7,
'Microsoft Entra ID SSO|||Đăng nhập một lần Microsoft Entra ID|||Microsoft Entra ID SSO',
'Single Sign-On (SSO) authentication for administrative and dispatch users via corporate Microsoft Entra ID.|||Xác thực đăng nhập một lần (SSO) cho người dùng quản trị và điều phối qua Microsoft Entra ID doanh nghiệp.|||Enkel inloggning (SSO) för administratörer och trafikledare via företagets Microsoft Entra ID.',
'Which Weride tenant, user groups, role mappings and conditional-access policies will be used?|||Sẽ dùng tenant Weride, nhóm người dùng, ánh xạ vai trò và chính sách truy cập có điều kiện nào?|||Vilken Weride-klientorganisation, användargrupper, rollmappning och villkorsstyrd åtkomst ska användas?',
['Confirm tenant registration and role mapping|||Xác nhận đăng ký tenant và ánh xạ vai trò|||Bekräfta klientregistrering och rollmappning','Implement SSO and server-side authorization|||Triển khai SSO và phân quyền phía máy chủ|||Implementera SSO och serverbaserad behörighetskontroll','Test revoked access, sessions and role boundaries|||Kiểm thử thu hồi quyền, phiên và giới hạn vai trò|||Testa återkallad åtkomst, sessioner och rollgränser'],
'The Madison-only login of this discovery workspace is separate from the Weride production SSO requirement.|||Đăng nhập riêng Madison của workspace discovery này tách biệt yêu cầu SSO sản phẩm Weride.|||Madison-inloggningen i denna discovery-arbetsyta är separat från Werides SSO-krav i produktion.')
req('REG-PWD-01','B',8,
'Algorithmic Disclosures Portal|||Cổng công bố thông tin thuật toán|||Portal för algoritmisk transparens',
'In-app driver interface presenting automated written disclosures detailing algorithmic task allocation parameters, performance tracking, and rating impacts.|||Giao diện trong ứng dụng tài xế trình bày công bố bằng văn bản tự động về tham số phân công thuật toán, theo dõi hiệu suất và tác động của đánh giá.|||Förargränssnitt i appen med automatiska skriftliga upplysningar om algoritmisk uppgiftsfördelning, prestationsuppföljning och betygspåverkan.',
'Who will approve the disclosure wording, language coverage and change-notification policy?|||Ai phê duyệt nội dung công bố, phạm vi ngôn ngữ và chính sách thông báo thay đổi?|||Vem godkänner upplysningarnas formulering, språkstöd och policy för ändringsmeddelanden?',
['Inventory algorithm inputs and driver impacts|||Lập danh mục đầu vào thuật toán và tác động tài xế|||Inventera algoritmindata och påverkan på förare','Build versioned driver-facing disclosure screens|||Xây dựng màn hình công bố có phiên bản cho tài xế|||Bygg versionshanterade upplysningsvyer för förare','Review disclosure coverage with legal stakeholders|||Rà soát phạm vi công bố cùng bên pháp lý|||Granska upplysningarnas täckning med juridiska intressenter'],
'Legal wording and applicability require Weride legal review; the RFP is recorded here, not independently certified.|||Nội dung và phạm vi pháp lý cần Weride rà soát; workspace ghi nhận RFP, không chứng nhận pháp lý độc lập.|||Juridisk formulering och tillämplighet kräver Werides granskning; RFP:n återges här utan oberoende certifiering.')
req('REG-PWD-02','B',8,
'Human Oversight Console|||Bảng giám sát của con người|||Konsol för mänsklig tillsyn',
'Administrative rule engine ensuring automated algorithms cannot execute driver account suspensions, financial penalties, or terminations without mandatory human dispatcher review and approval.|||Bộ quy tắc quản trị bảo đảm thuật toán không đình chỉ tài khoản tài xế, phạt tài chính hay chấm dứt nếu chưa được điều phối viên xem xét và phê duyệt bắt buộc.|||Administrativ regelmotor som hindrar algoritmer från att stänga av förarkonton, utfärda ekonomiska påföljder eller avsluta konton utan obligatorisk mänsklig granskning och godkännande.',
'Which actions require approval, who may approve them, and how are decisions and evidence retained?|||Hành động nào cần phê duyệt, ai được duyệt và quyết định/bằng chứng được lưu thế nào?|||Vilka åtgärder kräver godkännande, vem får godkänna och hur sparas beslut och underlag?',
['Model protected actions and approval roles|||Mô hình hoá hành động được bảo vệ và vai trò duyệt|||Modellera skyddade åtgärder och godkännanderoller','Build review queue and approval enforcement|||Xây dựng hàng đợi rà soát và bắt buộc phê duyệt|||Bygg granskningskö och tvingande godkännande','Test bypass resistance and decision traceability|||Kiểm thử chống bỏ qua phê duyệt và truy vết quyết định|||Testa skydd mot kringgående och spårbarhet'],
'No automated adverse driver action is assumed acceptable without the human review specified by the RFP.|||Không giả định cho phép tự động xử lý bất lợi với tài xế khi thiếu rà soát con người theo RFP.|||Ingen automatisk negativ föraråtgärd antas vara tillåten utan den mänskliga granskning som RFP:n anger.')
req('REG-PWD-03','B',8,
'Decision Explanation & Appeal SLA|||Giải thích quyết định và SLA khiếu nại|||Beslutsförklaring och SLA för överklaganden',
'Integrated ticketing console managing driver requests for explanations of automated decisions, tracking compliance against statutory review deadlines.|||Bảng quản lý yêu cầu tích hợp cho tài xế yêu cầu giải thích quyết định tự động và theo dõi đáp ứng thời hạn rà soát theo luật.|||Integrerad ärendekonsol för förares begäran om förklaring av automatiserade beslut och uppföljning av lagstadgade granskningstider.',
'What review deadlines, escalation rules and response templates have legal and operations approved?|||Pháp lý và vận hành đã duyệt thời hạn rà soát, quy tắc chuyển cấp và mẫu phản hồi nào?|||Vilka granskningstider, eskaleringsregler och svarsmallar har juridik och drift godkänt?',
['Define appeal lifecycle and configurable deadlines|||Định nghĩa vòng đời khiếu nại và thời hạn cấu hình|||Definiera ärendelivscykel och konfigurerbara tidsfrister','Implement explanation requests and escalation queue|||Triển khai yêu cầu giải thích và hàng đợi chuyển cấp|||Implementera förklaringsbegäran och eskaleringskö','Test deadline tracking and response evidence|||Kiểm thử theo dõi thời hạn và bằng chứng phản hồi|||Testa tidsuppföljning och svarsunderlag'],
'No statutory duration is hard-coded until the applicable rules and business calendar are confirmed.|||Không cố định thời lượng pháp định trong code trước khi xác nhận quy định áp dụng và lịch làm việc.|||Ingen lagstadgad tidslängd hårdkodas innan regler och verksamhetskalender har bekräftats.')
req('REG-PWD-04','B',8,
'Offline Telemetry Hard Stop|||Dừng cứng thu thập dữ liệu khi ngoại tuyến|||Absolut stopp för telemetri offline',
'Enforced software block preventing location tracking or background data collection whenever the driver application is in an offline or logged-off state.|||Chặn bắt buộc ở phần mềm để ngăn theo dõi vị trí hoặc thu thập dữ liệu nền khi ứng dụng tài xế ở trạng thái ngoại tuyến hoặc đã đăng xuất.|||Tvingande programvaruspärr som förhindrar positionsspårning och bakgrundsinsamling när förarappen är offline eller utloggad.',
'How is offline availability distinguished from network loss, and what telemetry is prohibited in each state?|||Phân biệt trạng thái ngừng nhận chuyến với mất mạng thế nào, và cấm thu thập dữ liệu nào ở mỗi trạng thái?|||Hur skiljs offline-tillgänglighet från nätverksbortfall, och vilken telemetri är förbjuden i respektive tillstånd?',
['Define availability and telemetry state machine|||Định nghĩa máy trạng thái sẵn sàng và thu thập dữ liệu|||Definiera tillståndsmaskin för tillgänglighet och telemetri','Enforce stop on device and reject prohibited ingest|||Dừng trên thiết bị và từ chối dữ liệu thu thập bị cấm|||Stoppa på enheten och avvisa förbjuden inläsning','Verify background behavior on iOS and Android|||Xác minh hành vi chạy nền trên iOS và Android|||Verifiera bakgrundsbeteende på iOS och Android'],
'Offline-state semantics require explicit approval; network loss must not be silently treated as equivalent.|||Ngữ nghĩa trạng thái ngoại tuyến cần phê duyệt rõ; không tự coi mất mạng là trạng thái tương đương.|||Betydelsen av offline-tillstånd måste godkännas uttryckligen; nätverksbortfall får inte likställas utan beslut.')
req('REG-PWD-05','B',8,
'Arbetsmiljöverket Reporting Export|||Xuất báo cáo Arbetsmiljöverket|||Rapportexport till Arbetsmiljöverket',
'Automated reporting module extracting platform worker counts, contract classifications, and operational conditions for Swedish authorities (Arbetsmiljöverket).|||Module báo cáo tự động trích xuất số lao động nền tảng, phân loại hợp đồng và điều kiện vận hành cho cơ quan Thụy Điển (Arbetsmiljöverket).|||Automatisk rapportmodul som tar fram antal plattformsarbetare, kontraktsklassificeringar och verksamhetsvillkor för svenska myndigheter (Arbetsmiljöverket).',
'Which reporting format, periodicity, classification rules and submission mechanism are required?|||Cần định dạng báo cáo, chu kỳ, quy tắc phân loại và cơ chế nộp nào?|||Vilket rapportformat, intervall, klassificeringsregler och inlämningssätt krävs?',
['Confirm report fields and classification ownership|||Xác nhận trường báo cáo và trách nhiệm phân loại|||Bekräfta rapportfält och klassificeringsansvar','Implement aggregation and export generation|||Triển khai tổng hợp và tạo tệp xuất|||Implementera aggregering och exportgenerering','Validate sample exports with responsible reviewers|||Xác thực tệp mẫu cùng người rà soát phụ trách|||Validera exempelrapporter med ansvariga granskare'],
'The final authority format and submission channel must be supplied or confirmed during discovery.|||Định dạng cuối và kênh nộp cơ quan chức năng cần được cung cấp hoặc xác nhận trong discovery.|||Myndighetens slutformat och inlämningskanal ska tillhandahållas eller bekräftas under discovery.')
req('REG-DAC-01','B',9,
'DAC 7 Identity Vault|||Kho định danh DAC 7|||Identitetsvalv för DAC 7',
'Secure storage capturing reportable driver data: Name, Address, Tax Identification Number (Personnummer/Organisationsnummer), VAT ID, DOB, and primary bank details.|||Lưu trữ an toàn dữ liệu tài xế cần báo cáo: tên, địa chỉ, mã số thuế (Personnummer/Organisationsnummer), mã VAT, ngày sinh và thông tin ngân hàng chính.|||Säker lagring av rapporterbara föraruppgifter: namn, adress, skatte-ID (personnummer/organisationsnummer), moms-ID, födelsedatum och huvudsakliga bankuppgifter.',
'Who is the reportable seller, how are identities validated, and what retention/access policies apply?|||Đối tượng bán hàng phải báo cáo là ai, định danh được xác thực thế nào và áp dụng chính sách lưu trữ/truy cập nào?|||Vem är rapporteringspliktig säljare, hur valideras identiteten och vilka lagrings-/åtkomstregler gäller?',
['Map identity fields and validation requirements|||Ánh xạ trường định danh và yêu cầu xác thực|||Kartlägg identitetsfält och valideringskrav','Implement protected storage and restricted access|||Triển khai lưu trữ bảo vệ và giới hạn truy cập|||Implementera skyddad lagring och begränsad åtkomst','Test data validation, masking and audit access|||Kiểm thử dữ liệu, che thông tin và nhật ký truy cập|||Testa validering, maskering och åtkomstloggning'],
'Seller classification and retention policy are pending tax/legal confirmation; no real identity data belongs in this workspace.|||Phân loại đối tượng và chính sách lưu trữ chờ xác nhận thuế/pháp lý; không đưa dữ liệu định danh thật vào workspace này.|||Säljarklassificering och lagringstid inväntar skatte-/juridikbekräftelse; verkliga identitetsuppgifter hör inte hemma i denna arbetsyta.')
req('REG-DAC-02','B',9,
'DAC 7 Activity Ledger|||Sổ hoạt động DAC 7|||Aktivitetsbokföring för DAC 7',
'Ledger tracking individual quarterly consideration paid, completed trip counts, and Weride platform fee deductions.|||Sổ theo dõi khoản chi trả theo quý cho từng cá nhân, số chuyến hoàn thành và khoản khấu trừ phí nền tảng Weride.|||Huvudbok som följer individuell kvartalsersättning, antal genomförda resor och avdrag för Werides plattformsavgifter.',
'How are corrections, refunds, commissions and payout timing reflected in quarterly consideration?|||Điều chỉnh, hoàn tiền, hoa hồng và thời điểm chi trả được phản ánh vào khoản thu theo quý thế nào?|||Hur påverkar korrigeringar, återbetalningar, provisioner och utbetalningstidpunkt kvartalsersättningen?',
['Specify ledger events and accounting boundaries|||Đặc tả sự kiện sổ và ranh giới kế toán|||Specificera huvudbokshändelser och redovisningsgränser','Implement quarterly aggregation and corrections|||Triển khai tổng hợp theo quý và điều chỉnh|||Implementera kvartalsaggregering och korrigeringar','Reconcile trip totals, fees and payout statements|||Đối soát tổng chuyến, phí và sao kê chi trả|||Stäm av resor, avgifter och utbetalningsbesked'],
'Accounting recognition and correction rules require approval before ledger design is finalized.|||Quy tắc ghi nhận và điều chỉnh kế toán cần được duyệt trước khi chốt thiết kế sổ.|||Regler för redovisning och korrigering ska godkännas innan huvudboksdesignen fastställs.')
req('REG-DAC-03','B',9,
'Skatteverket DAC 7 XML Exporter|||Xuất XML DAC 7 cho Skatteverket|||XML-export för DAC 7 till Skatteverket',
'One-click generator exporting annual platform tax data formatted strictly to official Skatteverket DAC 7 XML schemas.|||Công cụ một chạm xuất dữ liệu thuế nền tảng hàng năm đúng định dạng schema XML DAC 7 chính thức của Skatteverket.|||Enklicksgenerator som exporterar årliga plattformsskattedata strikt enligt Skatteverkets officiella DAC 7 XML-scheman.',
'Which schema version, correction-report flow and validation/submission process will be accepted?|||Phiên bản schema, luồng báo cáo điều chỉnh và quy trình kiểm tra/nộp nào được chấp nhận?|||Vilken schemaversion, korrigeringsrapportering och validerings-/inlämningsprocess godtas?',
['Obtain approved schemas and sample datasets|||Lấy schema được duyệt và dữ liệu mẫu|||Hämta godkända scheman och exempeldata','Build annual XML export and schema validation|||Xây dựng xuất XML hàng năm và kiểm tra schema|||Bygg årlig XML-export och schemavalidering','Test corrections, missing fields and tax-year boundaries|||Kiểm thử điều chỉnh, thiếu trường và ranh giới năm thuế|||Testa korrigeringar, saknade fält och skatteårsgränser'],
'XML export does not automatically imply direct electronic filing; submission responsibility is unresolved.|||Xuất XML không mặc định bao gồm nộp điện tử trực tiếp; trách nhiệm nộp chưa được chốt.|||XML-export innebär inte automatiskt direkt elektronisk inlämning; inlämningsansvaret är inte fastställt.')
req('REG-SWE-01','B',9,
'Prop. 2017/18:239 Audit Control Log|||Nhật ký kiểm toán theo Prop. 2017/18:239|||Kontrollogg enligt Prop. 2017/18:239',
'Encrypted, tamper-proof pre-booking audit log recording pre-agreed pricing, route GPS coordinates, driver ID, and timestamps for taximeter-exempt operation.|||Nhật ký kiểm toán đặt trước được mã hoá, chống sửa đổi, lưu giá thoả thuận trước, toạ độ GPS lộ trình, mã tài xế và dấu thời gian cho vận hành miễn đồng hồ tính cước.|||Krypterad, manipulationssäker förbokningslogg med förhandsavtalat pris, GPS-rutt, förar-ID och tidsstämplar för taxameterbefriad drift.',
'What certified equipment, reporting-center obligations and audit retention apply to Weride’s operating model?|||Mô hình Weride áp dụng nghĩa vụ thiết bị chứng nhận, trung tâm báo cáo và lưu kiểm toán nào?|||Vilka krav på certifierad utrustning, redovisningscentral och logglagring gäller för Werides driftsmodell?',
['Validate operating model and audit event specification|||Xác thực mô hình vận hành và đặc tả sự kiện kiểm toán|||Validera driftsmodell och specifikation för logghändelser','Design integrity-protected pricing and route evidence|||Thiết kế bằng chứng giá/lộ trình bảo vệ tính toàn vẹn|||Utforma integritetsskyddade pris- och ruttunderlag','Test traceability, retention and export verification|||Kiểm thử truy vết, lưu trữ và xác minh xuất dữ liệu|||Testa spårbarhet, lagring och exportverifiering'],
'The RFP audit-log statement is not treated as proof that software alone satisfies transport certification obligations.|||Nội dung nhật ký trong RFP không được coi là bằng chứng phần mềm riêng lẻ đáp ứng nghĩa vụ chứng nhận vận tải.|||RFP:ns loggkrav betraktas inte som bevis för att enbart mjukvara uppfyller transportcertifieringskraven.')
req('REG-SWE-02','B',9,
'Multi-Tier Split VAT Engine|||Bộ máy VAT tách theo nhóm dịch vụ|||Motor för uppdelad moms i flera nivåer',
'Automated calculation engine applying 6% VAT for passenger transport services versus 25% VAT for parcel/courier deliveries.|||Bộ tính tự động áp dụng VAT 6% cho vận tải hành khách và 25% cho giao bưu kiện/chuyển phát.|||Automatisk beräkningsmotor som tillämpar 6 % moms för persontransporter och 25 % för paket-/budleveranser.',
'Are courier services in L1, and how should mixed services, rounding, refunds and invoices be handled?|||Giao hàng có thuộc L1 không; xử lý dịch vụ hỗn hợp, làm tròn, hoàn tiền và hoá đơn thế nào?|||Ingår budtjänster i L1, och hur ska blandade tjänster, avrundning, återbetalningar och fakturor hanteras?',
['Define service tax categories and effective dates|||Định nghĩa nhóm thuế dịch vụ và ngày hiệu lực|||Definiera momskategorier och giltighetsdatum','Implement configurable tax calculation and allocation|||Triển khai tính và phân bổ thuế có cấu hình|||Implementera konfigurerbar momsberäkning och fördelning','Validate invoice, refund and rounding scenarios|||Xác thực kịch bản hoá đơn, hoàn tiền và làm tròn|||Validera faktura-, återbetalnings- och avrundningsfall'],
'The 6% and 25% rates are reproduced from the RFP, not independently verified tax advice.|||Mức 6% và 25% được ghi lại từ RFP, không phải tư vấn thuế đã xác minh độc lập.|||Satserna 6 % och 25 % återges från RFP:n och utgör inte oberoende verifierad skatterådgivning.')
req('REG-SWE-03','B',10,
'Fortnox/Stripe Accounting Export|||Xuất kế toán Fortnox/Stripe|||Redovisningsexport till Fortnox/Stripe',
'Automated transaction export routines feeding daily/bi-weekly sales and commission ledgers directly into Fortnox/Stripe accounting software, based on the payout cycle.|||Quy trình tự động xuất giao dịch vào sổ doanh thu và hoa hồng hàng ngày/hai tuần một lần của Fortnox/Stripe theo chu kỳ chi trả.|||Automatisk transaktionsexport av försäljnings- och provisionsböcker dagligen/varannan vecka direkt till Fortnox/Stripe enligt utbetalningscykeln.',
'What does “Fortnox/Stripe accounting software” mean operationally, and what cadence does “bi-weekly” denote?|||“Phần mềm kế toán Fortnox/Stripe” có nghĩa vận hành cụ thể gì và “bi-weekly” là chu kỳ nào?|||Vad avses operativt med ”Fortnox/Stripe accounting software”, och vilken frekvens avses med ”bi-weekly”?',
['Map charts of accounts, payouts and export cadence|||Ánh xạ hệ tài khoản, chi trả và chu kỳ xuất|||Kartlägg kontoplan, utbetalningar och exportintervall','Implement export adapters with retry and deduplication|||Triển khai bộ xuất có thử lại và chống trùng|||Implementera exportadaptrar med återförsök och dubblettskydd','Reconcile export totals and accounting acknowledgments|||Đối soát tổng xuất và xác nhận kế toán|||Stäm av exportsummor och bokföringsbekräftelser'],
'Provider responsibilities and the meaning of “bi-weekly” require clarification rather than silent interpretation.|||Trách nhiệm nhà cung cấp và nghĩa “bi-weekly” cần làm rõ, không tự diễn giải.|||Leverantörsansvar och betydelsen av ”bi-weekly” behöver klargöras och ska inte tolkas tyst.')
req('EXP-AI-01','C',11,
'Predictive Demand Heatmaps|||Bản đồ nhiệt dự báo nhu cầu|||Prognostiska efterfrågekartor',
'AI model overlaying historical trip density and local events to forecast high-demand zones.|||Mô hình AI kết hợp mật độ chuyến lịch sử và sự kiện địa phương để dự báo vùng nhu cầu cao.|||AI-modell som kombinerar historisk resetäthet och lokala evenemang för att prognostisera hög efterfrågan.',
'What historical data, event feeds and measurable forecast success criteria are available?|||Có dữ liệu lịch sử, nguồn sự kiện và tiêu chí đo chất lượng dự báo nào?|||Vilka historiska data, evenemangskällor och mätbara kvalitetskriterier finns?',
['Audit historical demand data and event sources|||Đánh giá dữ liệu nhu cầu lịch sử và nguồn sự kiện|||Granska historiska efterfrågedata och evenemangskällor','Prototype baseline forecast and heatmap overlay|||Thử nghiệm dự báo cơ sở và lớp bản đồ nhiệt|||Prototypa basprognos och värmekartslager','Evaluate forecast quality and operational usefulness|||Đánh giá chất lượng dự báo và giá trị vận hành|||Utvärdera prognoskvalitet och operativ nytta'],
'L2 forecasting depends on data quality and agreed evaluation; no accuracy or savings claim is assumed.|||Dự báo L2 phụ thuộc chất lượng dữ liệu và đánh giá thống nhất; không mặc định cam kết độ chính xác hay tiết kiệm.|||L2-prognoser beror på datakvalitet och avtalad utvärdering; ingen noggrannhet eller besparing förutsätts.')
req('EXP-FLT-01','C',11,
'Automated Flight Tracking Sync|||Đồng bộ theo dõi chuyến bay tự động|||Automatisk synkronisering av flygspårning',
'Flight tracking integration to automatically update pickup times and dispatch alerts based on real-time flight delays.|||Tích hợp theo dõi chuyến bay để tự động cập nhật giờ đón và cảnh báo điều phối theo chậm chuyến thời gian thực.|||Flygspårningsintegration som automatiskt uppdaterar hämtningstider och trafikledningslarm utifrån flygförseningar i realtid.',
'Which provider, airports, delay rules and cancelled/diverted-flight workflows are required?|||Cần nhà cung cấp, sân bay, quy tắc trễ và luồng xử lý chuyến huỷ/chuyển hướng nào?|||Vilken leverantör, flygplatser, förseningsregler och flöden för inställda/omdirigerade flyg krävs?',
['Confirm flight provider and matching identifiers|||Xác nhận nhà cung cấp và mã ghép chuyến bay|||Bekräfta flygleverantör och matchningsidentifierare','Implement delay sync and pickup rescheduling|||Triển khai đồng bộ trễ và đổi lịch đón|||Implementera förseningssynk och omplanerad hämtning','Test cancellations, diversions and dispatcher alerts|||Kiểm thử huỷ, đổi hướng và cảnh báo điều phối|||Testa inställda flyg, omdirigeringar och trafikledningslarm'],
'Flight tracking remains L2 in the matrix despite its mention in the ecosystem overview.|||Theo dõi chuyến bay vẫn là L2 trong matrix dù được nhắc ở tổng quan hệ sinh thái.|||Flygspårning är L2 i matrisen trots att den nämns i ekosystemöversikten.')
req('EXP-M365-01','C',11,
'Outlook Graph API Calendar Sync|||Đồng bộ lịch Outlook qua Graph API|||Outlook-kalendersynk via Graph API',
'Automated conversion of executive Outlook calendar appointments into scheduled ride bookings via Microsoft Graph API.|||Tự động chuyển lịch hẹn Outlook của lãnh đạo thành chuyến xe đặt trước qua Microsoft Graph API.|||Automatisk omvandling av chefers Outlook-möten till schemalagda resebokningar via Microsoft Graph API.',
'How are eligible appointments identified, consent obtained and updates/cancellations synchronized?|||Xác định lịch hẹn phù hợp, lấy đồng ý và đồng bộ thay đổi/huỷ thế nào?|||Hur identifieras relevanta möten, inhämtas samtycke och synkroniseras ändringar/avbokningar?',
['Define calendar permissions and booking eligibility|||Định nghĩa quyền lịch và điều kiện tạo chuyến|||Definiera kalenderbehörigheter och bokningsvillkor','Implement Graph subscriptions and booking sync|||Triển khai đăng ký Graph và đồng bộ chuyến|||Implementera Graph-prenumerationer och bokningssynk','Test recurrence, time zones and cancellation races|||Kiểm thử lịch lặp, múi giờ và xung đột huỷ|||Testa återkommande möten, tidszoner och avbokningskonflikter'],
'Calendar access is not included in baseline SSO consent and requires separate approved permissions.|||Quyền truy cập lịch không nằm trong đồng ý SSO cơ bản và cần được duyệt riêng.|||Kalenderåtkomst ingår inte i grundläggande SSO-samtycke utan kräver separata godkända behörigheter.')
req('EXP-M365-02','C',11,
'Power BI & Teams Emergency Pipelines|||Luồng Power BI và cảnh báo khẩn Teams|||Power BI-flöden och nödlarm i Teams',
'Continuous data pipelines feeding real-time operations into Power BI dashboards and routing panic triggers to Microsoft Teams channels.|||Luồng dữ liệu liên tục đưa vận hành thời gian thực lên Power BI và chuyển kích hoạt khẩn cấp đến kênh Microsoft Teams.|||Kontinuerliga dataflöden till Power BI-paneler i realtid och vidarebefordran av paniklarm till Microsoft Teams-kanaler.',
'What dashboard freshness, emergency acknowledgment and fallback channels are required?|||Cần độ mới dashboard, xác nhận cảnh báo khẩn và kênh dự phòng nào?|||Vilken aktualitet, larmkvittering och vilka reservkanaler krävs?',
['Define BI metrics and emergency escalation ownership|||Định nghĩa chỉ số BI và trách nhiệm xử lý khẩn|||Definiera BI-mått och ansvar för larmeskalering','Build operational data and Teams alert adapters|||Xây dựng bộ kết nối dữ liệu vận hành và cảnh báo Teams|||Bygg adaptrar för driftsdata och Teams-larm','Test delivery, acknowledgment and fallback handling|||Kiểm thử gửi, xác nhận và xử lý dự phòng|||Testa leverans, kvittering och reservhantering'],
'Teams delivery alone is not assumed to be a complete emergency-response service or SLA.|||Chỉ gửi đến Teams không được mặc định là dịch vụ ứng cứu khẩn hay SLA hoàn chỉnh.|||Leverans till Teams ensam förutsätts inte utgöra en fullständig larmtjänst eller SLA.')
req('EXP-PAS-01','C',11,
'In-App Fare Splitting|||Chia cước trong ứng dụng|||Delning av resekostnad i appen',
'Passenger app feature allowing riders to divide trip costs with other app users during an active ride.|||Tính năng hành khách chia chi phí chuyến đi với người dùng ứng dụng khác khi chuyến đang diễn ra.|||Funktion i passagerarappen för att dela resekostnaden med andra appanvändare under en pågående resa.',
'Who is liable if invited passengers decline or fail payment, and how are refunds split?|||Ai chịu trách nhiệm nếu người được mời từ chối/thanh toán thất bại, và chia hoàn tiền thế nào?|||Vem ansvarar om inbjudna passagerare avböjer eller inte betalar, och hur delas återbetalningar?',
['Define split invitations and liability rules|||Định nghĩa lời mời chia cước và trách nhiệm thanh toán|||Definiera delningsinbjudningar och betalningsansvar','Implement split-payment orchestration and status|||Triển khai điều phối thanh toán chia phần và trạng thái|||Implementera delbetalningsorkestrering och status','Test partial failure, cancellations and refunds|||Kiểm thử thất bại một phần, huỷ và hoàn tiền|||Testa partiella fel, avbokningar och återbetalningar'],
'Fare splitting is separately scoped L2 work and depends on the selected payment provider’s capabilities.|||Chia cước là phạm vi L2 riêng và phụ thuộc khả năng nhà cung cấp thanh toán được chọn.|||Kostnadsdelning är separat L2-arbete och beror på den valda betalningsleverantörens kapacitet.')
req('EXP-DRV-01','C',11,
'In-app economy (driver and passenger app)|||Hệ kinh tế trong ứng dụng tài xế và hành khách|||Ekonomi i förar- och passagerarappen',
'Configurable in-app points and subscription economy enabling drivers and passengers to earn, spend, receive, or redeem points based on booking activity, demand, behavior, and subscription tier, with dynamic incentives, access privileges, rewards, and administrative rule controls.|||Hệ điểm và gói đăng ký có cấu hình cho phép tài xế/hành khách kiếm, chi, nhận hoặc đổi điểm theo hoạt động đặt xe, nhu cầu, hành vi và hạng đăng ký; có ưu đãi linh hoạt, đặc quyền truy cập, phần thưởng và quản trị quy tắc.|||Konfigurerbar poäng- och prenumerationsekonomi där förare och passagerare tjänar, spenderar, tar emot eller löser in poäng utifrån bokningar, efterfrågan, beteende och prenumerationsnivå, med dynamiska incitament, åtkomstförmåner, belöningar och administrativ regelstyrning.',
'The matrix lists EXP-DRV-01, but §5.4 lists EXP-TAX-01 instead. Which L2 items must be priced?|||Matrix có EXP-DRV-01 nhưng mục 5.4 lại có EXP-TAX-01. Cần báo giá những mục L2 nào?|||Matrisen listar EXP-DRV-01 men avsnitt 5.4 listar i stället EXP-TAX-01. Vilka L2-delar ska prissättas?',
['Clarify economy scope and commercial-table mismatch|||Làm rõ phạm vi hệ điểm và khác biệt bảng thương mại|||Klargör ekonomins omfattning och avvikelsen i pristabellen','Design points ledger, subscription tiers and rules|||Thiết kế sổ điểm, hạng đăng ký và quy tắc|||Utforma poängbok, prenumerationsnivåer och regler','Validate redemption, reversals and abuse prevention|||Xác thực đổi điểm, hoàn tác và chống lạm dụng|||Validera inlösen, återföring och missbruksskydd'],
'Points have no assumed cash value or transferability; business, tax and legal treatment remain unresolved.|||Không mặc định điểm có giá trị tiền mặt hay chuyển nhượng; cách xử lý kinh doanh, thuế, pháp lý chưa chốt.|||Poäng antas inte ha kontantvärde eller överförbarhet; affärs-, skatte- och juridisk hantering är ännu inte fastställd.')

entries=[]
for r in rows:
    def entry(suffix,kind,title,body=None,parentId=''):
        return dict(id=r['id']+'-'+suffix,requirementId=r['id'],kind=kind,parentId=parentId,title=title,body=body or {'en':'','vi':'','sv':''},answer={'en':'','vi':'','sv':''},acceptance={'en':'','vi':'','sv':''},status={'qa':'open','breakdown':'todo','assumption':'unvalidated'}[kind],priority='high' if r['module']=='B' else 'medium',owner='',estimateHours=None,version=1,origin='proposal',createdBy='seed',updatedBy='seed',createdByName='Madison · working draft',updatedByName='Madison · working draft')
    entries.append(entry('q01','qa',r.pop('question')))
    tasks=r.pop('tasks')
    entries.append(entry('b01','breakdown',tasks[0],tr('Proposed discovery work package. Scope and acceptance criteria need team review.|||Gói công việc discovery đề xuất. Phạm vi và tiêu chí nghiệm thu cần nhóm rà soát.|||Föreslaget discovery-arbetspaket. Omfattning och acceptanskriterier behöver granskas av teamet.')))
    entries.append(entry('b02','breakdown',tasks[1],parentId=r['id']+'-b01'))
    entries.append(entry('b03','breakdown',tasks[2],parentId=r['id']+'-b01'))
    entries.append(entry('a01','assumption',r.pop('assumption')))
    r['order']=len([x for x in rows[:rows.index(r)]])+1
project={
'id':'weride','name':'WeRide','client':'Weride Sweden AB','reference':'WERIDE-RFP-2026-Version 3','sourceFile':'WeRide Discovery & Vendor RFP Package 2026 1.pdf',
'summary':tr('Next-generation ride-hailing, dispatch and fleet operations. One shared space to turn the RFP into a clear, reviewable delivery scope.|||Nền tảng gọi xe, điều phối và vận hành đội xe thế hệ mới. Không gian chung chuyển RFP thành phạm vi triển khai rõ ràng, có thể rà soát.|||Nästa generations plattform för taxibokning, trafikledning och flottverksamhet. En gemensam plats för att omvandla RFP:n till en tydlig och granskningsbar leveransomfattning.'),
'fleetReference':150,'fleetReferencePage':15,
'milestones':[
{'key':'released','date':'2026-09-25','page':0}, {'key':'intent','date':'2026-10-05','page':0}, {'key':'questions','date':'2026-10-10','page':0}, {'key':'submission','date':'2026-10-14','time':'17:00 CET','page':0}, {'key':'award','date':'2026-10-20','page':0}],
'clarifications':[
{'id':'deadline','title':tr('Submission date conflict|||Mâu thuẫn hạn nộp|||Motstridigt inlämningsdatum'),'body':tr('Cover: 14 October 2026, 17:00 CET. Section 5.0: 30 October 2026. Confirm the deadline and time zone with Weride; neither is silently substituted.|||Trang bìa: 14/10/2026, 17:00 CET. Mục 5.0: 30/10/2026. Cần Weride xác nhận hạn và múi giờ; không tự thay thế.|||Omslag: 14 oktober 2026, 17:00 CET. Avsnitt 5.0: 30 oktober 2026. Bekräfta datum och tidszon med Weride; inget ersätts utan beslut.'),'pages':'Cover / §5.0, p.13'},
{'id':'expansion','title':tr('L2 matrix / pricing-table mismatch|||Lệch matrix L2 và bảng báo giá|||Avvikelse mellan L2-matris och pristabell'),'body':tr('Section 3 contains EXP-DRV-01 (in-app economy). Section 5.4 instead contains EXP-TAX-01 (Digital Driving Log / Körjournal), which has no requirement row in Section 3. The matrix remains unchanged.|||Mục 3 có EXP-DRV-01 (hệ kinh tế trong app). Mục 5.4 lại có EXP-TAX-01 (nhật ký lái xe / Körjournal), không có dòng yêu cầu ở mục 3. Giữ nguyên matrix.|||Avsnitt 3 innehåller EXP-DRV-01 (ekonomi i appen). Avsnitt 5.4 innehåller i stället EXP-TAX-01 (digital körjournal), som saknar kravrad i avsnitt 3. Matrisen lämnas oförändrad.'),'pages':'§3, p.11 / §5.4, p.16'}]
}
assert len(rows)==30 and sum(r['tier']=='L1' for r in rows)==24
assert len({r['id'] for r in rows})==30
out={'schemaVersion':1,'project':project,'requirements':rows,'entries':entries}
(ROOT/'private'/'seed.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(f'Wrote {len(rows)} source requirements and {len(entries)} clearly labeled proposal work items.')
