from pathlib import Path
p=Path('src/pages/Search.tsx')
s=p.read_text()
s="import {useState,useEffect} from 'react';\n"+s
s=s.replace("  const needle=q.trim().toLocaleLowerCase();", "  const needle=q.trim().toLocaleLowerCase();const [visibleCount,setVisibleCount]=useState(100);\n  useEffect(()=>setVisibleCount(100),[q,type,status]);")
s=s.replace('group.slice(0,type?100:8)','group.slice(0,type?visibleCount:8)')
s=s.replace("          {!type&&group.length>8&&", "          {type&&group.length>visibleCount&&<button className=\"button secondary small\" onClick={()=>setVisibleCount(n=>n+100)}>{t('aiLoadMore')}</button>}\n          {!type&&group.length>8&&")
p.write_text(s)
p=Path('src/lib/preferences.ts')
s=p.read_text().replace("const change=()=>setDensity(read());", "const change=(event:Event)=>setDensity((event as CustomEvent<Density>).detail||read());")
s=s.replace("window.dispatchEvent(new Event('weride:density'));", "window.dispatchEvent(new CustomEvent('weride:density',{detail:value}));")
p.write_text(s)
p=Path('src/lib/draft-storage.ts')
s=p.read_text().replace("const memory=new Map<string,DraftRecord>();", "const memory=new Map<string,DraftRecord>();\nconst suppressed=new Set<string>();")
s=s.replace("if(r&&typeof r.uid", "if(!suppressed.has(key)&&r&&typeof r.uid")
s=s.replace("const now=Date.now();memory.set", "const now=Date.now();suppressed.delete(compound(uid,key));memory.set")
s=s.replace("listDrafts(uid);memory.delete(compound(uid,key));", "listDrafts(uid);suppressed.add(compound(uid,key));memory.delete(compound(uid,key));")
s=s.replace("if(r.uid===uid)memory.delete(key);", "if(r.uid===uid){suppressed.add(key);memory.delete(key);}")
p.write_text(s)
print('Large search groups can load every result; blocked preference storage retains current UI choice; cleared drafts cannot reappear from a stale storage read.')
